name: Release

on:
  push:
    branches:
      - main
      - 'release-test*'  # Only run on branches with release-test prefix
  pull_request:
    types: [ labeled, unlabeled ]

permissions: {}

jobs:
  release-pr:
    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write
    runs-on: ubuntu-latest
    outputs:
      state: ${{ steps.release-pr.outputs.state }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create or update release PR
        id: release-pr
        uses: actionutils/create-release-pr@079c40c8d40e2793f3d949528daa6a202cd9d4af

  verify-releaser:
    needs: [release-pr]
    if: needs.release-pr.outputs.state == 'release_required'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - name: Verify Trusted Tag Releaser
        uses: actionutils/trusted-tag-verifier@v0
        with:
          verify: 'actionutils/trusted-tag-releaser@v2'

  release:
    needs: [verify-releaser, release-pr]
    if: needs.release-pr.outputs.state == 'release_required'
    concurrency:
      group: "release"
      cancel-in-progress: false
    permissions:
      id-token: write    # Required for signed tags
      contents: write    # Required for release and tag creation
      pull-requests: write # Required for bumpr commenting
      attestations: write # Required for build provenance attestation
      actions: read      # Required for SLSA generator
    uses: actionutils/trusted-tag-releaser/.github/workflows/trusted-release-workflow.yml@v2
    with:
      environment: release
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
